metadata.format.version = "1.1"

[versions]

gson = "2.10.1"
fastutil = "8.5.12"
vianbt = "5.0.0"
mcstructs = "5-2.5.1"

# Common provided
netty = "4.0.20.Final"
guava = "17.0"
snakeYaml = "2.2"

junit = "5.10.2"
checkerQual = "3.43.0"

# Platforms
paper = "1.20.4-R0.1-SNAPSHOT"
legacyBukkit = "1.8.8-R0.1-SNAPSHOT"
velocity = "3.1.1"


[libraries]

gson = { group = "com.google.code.gson", name = "gson", version.ref = "gson" }
fastutil = { group = "it.unimi.dsi", name = "fastutil", version.ref = "fastutil" }
vianbt = { group = "com.viaversion", name = "nbt", version.ref = "vianbt" }
# Custom version that uses ViaNBT instead of its own inbuilt NBT library
text = { group = "com.viaversion.mcstructs", name = "text", version.ref = "mcstructs" }

netty = { group = "io.netty", name = "netty-all", version.ref = "netty" }
guava = { group = "com.google.guava", name = "guava", version.ref = "guava" }
snakeYaml = { group = "org.yaml", name = "snakeyaml", version.ref = "snakeYaml" }

jupiterApi = { group = "org.junit.jupiter", name = "junit-jupiter-api", version.ref = "junit" }
jupiterEngine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
checkerQual = { group = "org.checkerframework", name = "checker-qual", version.ref = "checkerQual" }

paper = { group = "io.papermc.paper", name = "paper-api", version.ref = "paper" }
legacyBukkit = { group = "org.bukkit", name = "bukkit", version.ref = "legacyBukkit" }
velocity = { group = "com.velocitypowered", name = "velocity-api", version.ref = "velocity" }


[bundles]

junit = ["jupiterApi", "jupiterEngine"]
